### ISSUE TITLE
Genes with all zero counts triggers Error in order(..., decreasing = decreasing) : argument 1 is not a vector

### ISSUE THREAD

**Issue by IanSudbery** [kokonech/InTAD#8]
findGeneCorrelation filters out genes with no counts in all samples. 

If all genes to be tested against a peak have zero counts then findGeneCorrelation returns NULL

If findGeneCorrelation returns NULL, then the follow line produces there error `Error in order(..., decreasing = decreasing) : argument 1 is not a vector`:
https://github.com/kokonech/InTAD/blob/3be7d855c7d90f384765e15c0f4cf8b353509edf/R/findCorrelation.R#L88

**Comment by kokonech** [comment]
Hi, thanks for the note! The error report in case either gene matrix fully filtered or consists only from zeroes is included in latest commit, it's currently available via bioconductor-dev:
https://bioconductor.org/packages/3.12/bioc/html/InTAD.html 
I did not include it the current Bioconductor version since the release will be quite soon (middle of October).

**Comment by IanSudbery** [comment]
thanks
